#include "../include/open_manipulator/OMAPI.h"
// #include "../include/open_manipulator/OMManager.h"
// #include "../include/open_manipulator/OMDynamixel.h"
// #include "../include/open_manipulator/OMDebug.h"
// #include "../include/open_manipulator/OMKinematics.h"
// #include "../include/open_manipulator/OMMath.h"
// #include "../include/open_manipulator/OMPath.h"